version: "3"

services:
    mysql:
        image: mysql:8.0
        volumes:
            - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
            - mysql-datastore:/var/lib/mysql
        environment:
            TZ: Asia/Tokyo
            MYSQL_ROOT_PASSWORD: mysql

    app:
        build: ./app
        volumes:
            - ./app:/workdir:ro
        environment:
            TZ: Asia/Tokyo
        command: python3 app.py

    proxy:
        image: nginx:1.23-alpine
        ports:
            - ${PORT}:80
        volumes:
            - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
        environment:
            TZ: Asia/Tokyo
        depends_on:
            - app

volumes:
    mysql-datastore:
        driver: local
