version: "3"
services:
    app:
        build: ./app
        volumes:
            - ./app:/workdir:ro
        environment:
            TZ: Asia/Tokyo
        command: python3 app.py

    proxy:
        image: nginx:1.23-alpine
        ports:
            - ${PORT}:80
        volumes:
            - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
        environment:
            TZ: Asia/Tokyo
        depends_on:
            - app
 